# Generated by Django 4.2.3 on 2023-07-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_authormodel_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
